208612048 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #[#$%释放MySQLOper:3]
208612053 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@2e0c3688com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612054 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612054 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@2e0c3688用时[3] SQL:[core.DBLoaderEx$SaveGlobalMethod@2e0c3688]
208612060 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6aa372b7com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612060 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612061 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6aa372b7用时[7] SQL:[core.DBLoaderEx$SaveGlobalMethod@6aa372b7]
208612061 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@25e2d3a6com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612061 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612061 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@25e2d3a6用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@25e2d3a6]
208612062 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1f51bbbecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612062 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612062 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1f51bbbe用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@1f51bbbe]
208612062 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6e4a6aebcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612062 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612063 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6e4a6aeb用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@6e4a6aeb]
208612063 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@20ceb2cecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612063 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612063 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@20ceb2ce用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@20ceb2ce]
208612063 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@77ea7354com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612063 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612066 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@77ea7354用时[3] SQL:[core.DBLoaderEx$SaveGlobalMethod@77ea7354]
208612066 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@131d4f6dcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612066 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612067 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@131d4f6d用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@131d4f6d]
208612067 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@2fb5fed4com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612067 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612067 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@2fb5fed4用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@2fb5fed4]
208612067 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@16971fefcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612067 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612080 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@16971fef用时[13] SQL:[core.DBLoaderEx$SaveGlobalMethod@16971fef]
208612081 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@175526cecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612081 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612081 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@175526ce用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@175526ce]
208612081 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@142c4d56com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612081 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612081 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@142c4d56用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@142c4d56]
208612082 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@c0c3ebecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612082 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612082 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@c0c3ebe用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@c0c3ebe]
208612140 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1212135ecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612140 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612140 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1212135e用时[58] SQL:[core.DBLoaderEx$SaveGlobalMethod@1212135e]
208612149 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@4506647fcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612149 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612149 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@4506647f用时[9] SQL:[core.DBLoaderEx$SaveGlobalMethod@4506647f]
208612149 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@367c2cb1com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612149 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612150 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@367c2cb1用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@367c2cb1]
208612150 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@7a379eb2com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612150 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612151 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@7a379eb2用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@7a379eb2]
208612151 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@2b0598bbcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612151 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208612151 2017-07-03 09:31:55 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@2b0598bb用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@2b0598bb]
208612153 2017-07-03 09:31:55 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@407ecd3bcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208612154 2017-07-03 09:31:55 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:31:55',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208613050 2017-07-03 09:31:56 [GlobalLog] SQL INSERT INTO _LogicInfoLog (ServerID,Tm,ProcessLogicNum,ProcessLogicTotalNum,SQLListNum,LogicListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:31:56',18,223,0,0,1)
208618385 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@407ecd3b用时[6233] SQL:[core.DBLoaderEx$SaveGlobalMethod@407ecd3b]
208618386 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6206c1c2[逻辑]用时[5335]过多,连接数[0]用户数[0],细则
UpdateTimer:0
UpdateFrame:0
UpdateUser:0

208618386 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6206c1c2com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618386 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618386 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6206c1c2用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@6206c1c2]
208618387 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@281e8b1com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618387 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618387 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@281e8b1用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@281e8b1]
208618387 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@399f548ecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618387 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618387 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@399f548e用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@399f548e]
208618388 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@7a5821ecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618388 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618388 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@7a5821e用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@7a5821e]
208618388 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@35eef98fcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618388 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618389 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@35eef98f用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@35eef98f]
208618389 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO _SQLInfoLog (ServerID,Tm,ProcessSQLNum,ProcessSQLTotalNum,ListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:02',24,222,51,7089)
208618389 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #[SQL执行]用时[6338]过多,连接数[0]用户数[0],细则
core.DBLoaderEx$SaveGlobalMethod@2e0c3688,0,3
core.DBLoaderEx$SaveGlobalMethod@6aa372b7,0,7
core.DBLoaderEx$SaveGlobalMethod@25e2d3a6,0,0
core.DBLoaderEx$SaveGlobalMethod@1f51bbbe,0,1
core.DBLoaderEx$SaveGlobalMethod@6e4a6aeb,0,1
core.DBLoaderEx$SaveGlobalMethod@20ceb2ce,0,0
core.DBLoaderEx$SaveGlobalMethod@77ea7354,0,3
core.DBLoaderEx$SaveGlobalMethod@131d4f6d,0,1
core.DBLoaderEx$SaveGlobalMethod@2fb5fed4,0,0
core.DBLoaderEx$SaveGlobalMethod@16971fef,0,13
core.DBLoaderEx$SaveGlobalMethod@175526ce,0,1
core.DBLoaderEx$SaveGlobalMethod@142c4d56,0,0
core.DBLoaderEx$SaveGlobalMethod@c0c3ebe,0,1
core.DBLoaderEx$SaveGlobalMethod@1212135e,0,58
core.DBLoaderEx$SaveGlobalMethod@4506647f,0,9
core.DBLoaderEx$SaveGlobalMethod@367c2cb1,0,1
core.DBLoaderEx$SaveGlobalMethod@7a379eb2,0,1
core.DBLoaderEx$SaveGlobalMethod@2b0598bb,0,0
core.DBLoaderEx$SaveGlobalMethod@407ecd3b,0,6233
core.DBLoaderEx$SaveGlobalMethod@6206c1c2,0,0
core.DBLoaderEx$SaveGlobalMethod@281e8b1,0,1
core.DBLoaderEx$SaveGlobalMethod@399f548e,0,0
core.DBLoaderEx$SaveGlobalMethod@7a5821e,0,1
core.DBLoaderEx$SaveGlobalMethod@35eef98f,0,1

208618393 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@75cbd4a1com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618393 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618393 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@75cbd4a1用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@75cbd4a1]
208618394 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@76bbee2acom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618394 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618394 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@76bbee2a用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@76bbee2a]
208618394 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@2b1d77accom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618394 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618394 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@2b1d77ac用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@2b1d77ac]
208618395 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6c162bf9com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618395 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618395 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6c162bf9用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@6c162bf9]
208618395 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6ac6e7dbcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618395 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618396 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6ac6e7db用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@6ac6e7db]
208618396 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@58f6d4a9com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618396 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618396 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@58f6d4a9用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@58f6d4a9]
208618396 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1dc4ea0ecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618396 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618397 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1dc4ea0e用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@1dc4ea0e]
208618397 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@65fdb3e2com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618397 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618397 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@65fdb3e2用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@65fdb3e2]
208618397 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@16d46fb5com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618397 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618397 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@16d46fb5用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@16d46fb5]
208618398 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@161b875acom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618398 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618398 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@161b875a用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@161b875a]
208618398 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@5c273df6com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618398 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618399 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@5c273df6用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@5c273df6]
208618399 2017-07-03 09:32:02 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@207ebdacom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208618399 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:02',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208618399 2017-07-03 09:32:02 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@207ebda用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@207ebda]
208618962 2017-07-03 09:32:02 [GlobalLog] SQL INSERT INTO _SQLInfoLog (ServerID,Tm,ProcessSQLNum,ProcessSQLTotalNum,ListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:02',12,234,39,7089)
208619386 2017-07-03 09:32:03 [GlobalLog] SQL INSERT INTO _LogicInfoLog (ServerID,Tm,ProcessLogicNum,ProcessLogicTotalNum,SQLListNum,LogicListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:03',18,241,0,0,5335)
208620346 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@54d7b03bcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620346 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620347 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@54d7b03b用时[1382] SQL:[core.DBLoaderEx$SaveGlobalMethod@54d7b03b]
208620347 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@45d5d9c8com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620347 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620347 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@45d5d9c8用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@45d5d9c8]
208620348 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@4aed11afcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620348 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620348 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@4aed11af用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@4aed11af]
208620348 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@54f8d1b1com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620348 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620348 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@54f8d1b1用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@54f8d1b1]
208620349 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@4406dbbdcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620349 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620349 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@4406dbbd用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@4406dbbd]
208620350 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@2bb40c32com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620350 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620350 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@2bb40c32用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@2bb40c32]
208620359 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO _SQLInfoLog (ServerID,Tm,ProcessSQLNum,ProcessSQLTotalNum,ListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:04',6,240,33,7089)
208620361 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #[SQL执行]用时[1396]过多,连接数[0]用户数[0],细则
core.DBLoaderEx$SaveGlobalMethod@54d7b03b,0,1382
core.DBLoaderEx$SaveGlobalMethod@45d5d9c8,0,0
core.DBLoaderEx$SaveGlobalMethod@4aed11af,0,1
core.DBLoaderEx$SaveGlobalMethod@54f8d1b1,0,0
core.DBLoaderEx$SaveGlobalMethod@4406dbbd,0,1
core.DBLoaderEx$SaveGlobalMethod@2bb40c32,0,1

208620362 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@19ec1bd7com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620362 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620362 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@19ec1bd7用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@19ec1bd7]
208620363 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@327e0d27com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620363 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620363 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@327e0d27用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@327e0d27]
208620363 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@fc5560acom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620363 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620363 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@fc5560a用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@fc5560a]
208620364 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@7616e5eecom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620364 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620364 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@7616e5ee用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@7616e5ee]
208620365 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@5385e464com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620365 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620365 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@5385e464用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@5385e464]
208620365 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@381f64c6com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620365 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620365 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@381f64c6用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@381f64c6]
208620366 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1e878c15com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620366 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620366 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1e878c15用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@1e878c15]
208620366 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1a61fdbacom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620366 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620366 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1a61fdba用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@1a61fdba]
208620367 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@356377dfcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620367 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620367 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@356377df用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@356377df]
208620367 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@25bcc6a8com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620367 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620367 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@25bcc6a8用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@25bcc6a8]
208620368 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@297be0c2com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620368 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620370 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@297be0c2用时[3] SQL:[core.DBLoaderEx$SaveGlobalMethod@297be0c2]
208620371 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@7186f998com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620371 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620371 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@7186f998用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@7186f998]
208620371 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@4554cd28com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620372 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620372 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@4554cd28用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@4554cd28]
208620372 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@5646f75dcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620372 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620372 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@5646f75d用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@5646f75d]
208620373 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@7c3dfcf3com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620373 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620373 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@7c3dfcf3用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@7c3dfcf3]
208620373 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@599944edcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620373 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620373 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@599944ed用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@599944ed]
208620374 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@4f4bfbeccom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620374 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620374 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@4f4bfbec用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@4f4bfbec]
208620375 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@41fa33e9com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620375 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620375 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@41fa33e9用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@41fa33e9]
208620377 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1fc5d6b4com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620377 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620378 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1fc5d6b4用时[3] SQL:[core.DBLoaderEx$SaveGlobalMethod@1fc5d6b4]
208620378 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6053e213com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620378 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620378 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6053e213用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@6053e213]
208620379 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@5013645acom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620379 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620379 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@5013645a用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@5013645a]
208620380 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@68dabd82com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620380 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620380 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@68dabd82用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@68dabd82]
208620381 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@51f5fffacom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620381 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620381 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@51f5fffa用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@51f5fffa]
208620381 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@4f8b8882com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620382 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620382 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@4f8b8882用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@4f8b8882]
208620382 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@50db3577com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620382 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620382 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@50db3577用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@50db3577]
208620382 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@319a76b6com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620383 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620383 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@319a76b6用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@319a76b6]
208620383 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@6eb1a84ccom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620383 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620383 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@6eb1a84c用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@6eb1a84c]
208620384 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@1f062fb2com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620384 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620384 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@1f062fb2用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@1f062fb2]
208620384 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@59b1b3eccom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620384 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620384 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@59b1b3ec用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@59b1b3ec]
208620385 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@544762efcom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620385 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620385 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@544762ef用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@544762ef]
208620385 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@3653aececom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620385 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620386 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@3653aece用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@3653aece]
208620388 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO _LogicInfoLog (ServerID,Tm,ProcessLogicNum,ProcessLogicTotalNum,SQLListNum,LogicListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:04',37,278,0,0,1)
208620471 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@36dc0fc4com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620471 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620471 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@36dc0fc4用时[85] SQL:[core.DBLoaderEx$SaveGlobalMethod@36dc0fc4]
208620472 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@352e5a90com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620472 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620472 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@352e5a90用时[1] SQL:[core.DBLoaderEx$SaveGlobalMethod@352e5a90]
208620862 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO _SQLInfoLog (ServerID,Tm,ProcessSQLNum,ProcessSQLTotalNum,ListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:04',33,273,0,7089)
208620946 2017-07-03 09:32:04 [GlobalLog] SYSTEM_ERROR #core.DBLoaderEx$SaveGlobalMethod@208a6a2acom.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
208620946 2017-07-03 09:32:04 [GlobalLog] SQL INSERT INTO ExceptionLog (ServerID,Tm,RoleID,ExceptionName,Detail) VALUES (18,'2017-07-03 09:32:04',0,'com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.','sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
java.lang.reflect.Constructor.newInstance(Unknown Source)
com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
com.mysql.jdbc.Util.getInstance(Util.java:386)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1251)
com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1243)
com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1674)
core.db.mysql.MySQLDBReader.Commit(MySQLDBReader.java:63)
core.DBMgr.Commit(DBMgr.java:52)
core.DBLoaderEx$SaveGlobalSQLRun.Execute(DBLoaderEx.java:35)
core.CustomMethod.SqlRun(CustomMethod.java:63)
core.detail.impl.mgr.SqlMgrImpl._ExecuteSQL(SqlMgrImpl.java:194)
core.detail.impl.mgr.SqlMgrImpl.run(SqlMgrImpl.java:119)
java.lang.Thread.run(Unknown Source)
')
208620946 2017-07-03 09:32:04 [GlobalLog] SYSTEM_INFO #core.DBLoaderEx$SaveGlobalMethod@208a6a2a用时[0] SQL:[core.DBLoaderEx$SaveGlobalMethod@208a6a2a]
208621364 2017-07-03 09:32:05 [GlobalLog] SQL INSERT INTO _SQLInfoLog (ServerID,Tm,ProcessSQLNum,ProcessSQLTotalNum,ListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:05',1,274,0,7089)
208621389 2017-07-03 09:32:05 [GlobalLog] SQL INSERT INTO _LogicInfoLog (ServerID,Tm,ProcessLogicNum,ProcessLogicTotalNum,SQLListNum,LogicListNum,UpdateMaxTime) VALUES (18,'2017-07-03 09:32:05',3,281,0,0,15)
